### ISSUE TITLE
a config to disable yeeting in the bazaar between time

### ISSUE THREAD

**Issue by Littleevo** [ThinkInvis/RoR2-Yeet#16] opened 2022-08-21 22:10 UTC
when using items in a printer / cauldron, there's the risk/reward decision you have to make on whether you're willing to gamble the items that you want vs. the items that you might print. you can also instead choose to drop all of the items that you need and print away the ones that you don't like, but that can expose you to a sudden enemy attack, leaving you defenseless for a few seconds which can lead to your death.
in the bazaar between time however, that risk isn't there anymore. there's no more reason to gamble with your items when you can comfortably drop your desired items on the ground.

a config to disable yeeting in the bazaar can be a nice way to fix this.

an alternate solution that i can come up with is to include items on the ground when deciding which items to print / combine in a cauldron. but i don't know how awkward it might be to code / play with.

**Comment by ThinkInvis** [comment] 2022-08-23 01:41
Duplicate of #9. As mentioned there, the best fitting solution to this *that I was/am willing to implement* was/is a steep cooldown.

**Closed as completed by ThinkInvis** 2022-08-23 01:41 UTC
Labels: duplicate, cantfix/wontfix
