### ISSUE TITLE
Config to change number of items dropped / prevent tiers from dropping

### ISSUE THREAD

**Issue by quakeman00** [ThinkInvis/RoR2-Yeet#13] opened 2022-07-01 22:38 UTC
i would like to know if it could be possible to add a config to decide how many items are tossed at once and other configs for the tiers of items (mostly red so people who pick benthic bloom don't go and drop 32958 reds afterward but yellows and greens could also be considered.

**Comment by ThinkInvis** [comment] 2022-07-04 03:13
Partial duplicate of #8. I'm considering implementation details for quantity options now.

**Closed as completed** 2022-07-04 13:38 UTC
Labels: enhancement
